### ISSUE TITLE
Add DNS record for old-docs.janusgraph.org

### ISSUE THREAD

**Issue by porunov** [JanusGraph/old-docs.janusgraph.org#39]
The Linux Foundation members should add a new DNS record for `old-docs.janusgraph.org` which looks identical to `docs.janusgraph.org`. This DNS record should point to GitHub ip addresses.

After that we can add a link from new documentation to old documentation.

**Comment by porunov** [comment]
@mbrukman @jmertic Can I as you please to contact responsible members and ask them to add this DNS record?

**Comment by jmertic** [comment]
I've contacted our IT to make the DNS add - hopefully should get added quickly.

**Comment by porunov** [comment]
@jmertic Thank you!

**Comment by jmertic** [comment]
Should be live now - might take a bit for the DNS to propagate.

**Comment by porunov** [comment]
Thank you! The old JanusGraph documentation is now live
